version: '3.9'

name: 'gitlab'

networks:
  default:
    name: 'gitlab'

volumes:
  gl-config:
  gl-logs:
  gl-data:

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - 'gl-config:/etc/gitlab'
      - 'gl-logs:/var/log/gitlab'
      - 'gl-data:/var/opt/gitlab'
    shm_size: '256m'

  runner-1:
    image: gitlab/gitlab-runner:latest
    restart: always
    hostname: 'gitlab.runner-1.com'
    ports:
      - '8093:8093'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock '
      - './runner-config.toml:/etc/gitlab-runner/config.toml'


