version: '3.9'

networks:
  default :
    name: 'obg'

volumes : 
  obg-pg:    
  obg-logs:
  obg-os:  
  obg-prom:
  obg-grafana:
  
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'obg-pg'
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - obg-pg:/var/lib/postgresql/data
      
  opensearch:
    image: 'opensearchproject/opensearch:2.9.0'
    container_name: 'obg-os'  
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      discovery.type: single-node
      plugins.security.disabled: 'true'
    volumes:
      - obg-logs:/usr/share/opensearch/data


  opensearch-dashboards:
    image: 'opensearchproject/opensearch-dashboards:2.9.0'
    container_name: 'obg-osd'
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["http://obg-os:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch

  prometheus:
    container_name: "obg-prom"
    image: "prom/prometheus"
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - obg-prom:/prometheus
  
  grafana:
    container_name: 'obg-grafana'
    image: 'grafana/grafana'
    restart: unless-stopped
    environment :
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - obg-grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on: 
      - prometheus

  jaeger:
    container_name: 'obg-jaeger'
    image: 'jaegertracing/all-in-one:1.9'
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '9411:9411'      