version: '3.9'

networks:
  default :
    name: 'obg'

volumes : 
  obg-pg:    
  obg-logs:
  obg-os:  
  obg-prom:
  obg-grafana:
  
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'obg-pg'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - obg-pg:/var/lib/postgresql/data
     
  prometheus:
    container_name: "obg-prom"
    image: "prom/prometheus"
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - obg-prom:/prometheus

  loki:
    container_name: 'obg-loki'
    image: 'grafana/loki'
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: --config.file=/etc/loki/local-config.yml 


  grafana:
    container_name: 'obg-grafana'
    image: 'grafana/grafana'
    restart: unless-stopped
    environment :
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - obg-grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    depends_on: 
      - prometheus

  jaeger:
    container_name: 'obg-jaeger'
    image: 'jaegertracing/all-in-one:1.9'
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '9411:9411'  
  
  api:
    build:
      context: .
    container_name: 'obg-api'
    ports:
      - '8080:8080'
    environment:
      ConnectionStrings__Postgres: 'User ID=postgres;Password=admin;Host=obg-pg;Port=5432;Database=obg;Pooling=true;MinPoolSize=0;MaxPoolSize=100;Connection Idle Lifetime=60;'
      ConnectionStrings__Logs: 'http://obg-loki:3100'
      ConnectionStrings__Tracing: 'http://obg-jaeger:14268/api/traces'

      