global:
  scrape_interval: "10s"
  scrape_timeout: "3s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: obg-scrape
    metrics_path: 
    
    static_configs:
      - targets:
        - host.docker.internal:7159
        labels:
          app: obg
